#!/usr/bin/env bash
# =============================================================================
# adapters/opencode/adapter.sh - OpenCode platform adapter
# =============================================================================
# OpenCode reads AGENTS.md (the cross-IDE convention) at the project root.
# Same overall shape as the Codex adapter; the layout uses .opencode/.
# =============================================================================

OPENCODE_PLATFORM="opencode"
OPENCODE_DIR="opencode"
OPENCODE_DISPATCHER="AGENTS.md"

adapter_build() {
  local src="$1" dst="$2"

  _opencode_emit_dispatcher "$src" "$dst"
  _opencode_translate_commands "$src/commands" "$dst/.${OPENCODE_DIR}/commands"
  _opencode_copy_references "$src/references" "$dst/.${OPENCODE_DIR}/references"
  _opencode_copy_scripts "$src/scripts" "$dst/.${OPENCODE_DIR}/scripts"
  _opencode_emit_install_hint "$dst"
}

_opencode_emit_dispatcher() {
  local src="$1" dst="$2"
  local out="$dst/$OPENCODE_DISPATCHER"

  {
    cat <<'EOF'
# Obsidian Second Brain - OpenCode Operating Manual

This vault runs the **obsidian-second-brain** skill. The skill ships a set of
*commands*: each one is a multi-step instruction file that you (the OpenCode
agent) should follow when the user's request matches its trigger phrase.

## How to operate

1. Read `index.md` in the vault root first, if it exists; it is the canonical
   OKF bundle entrypoint. If `_CLAUDE.md` also exists, treat it as an optional
   extension file for local workflow rules.
2. When the user's request matches a trigger in the tables below, read the
   matching file under `.opencode/commands/<name>.md` and follow its
   instructions step by step.
3. Treat the OKF-first bundle contract (`index.md`, `log.md`, UTF-8 Markdown,
   required `type`, relative Markdown links) as non-negotiable. If the fork
   also exposes AI-first extension files, apply them too: `## For future Claude`
   preamble, richer frontmatter, recency markers, sources verbatim, and
   confidence levels. Obsidian `[[wikilinks]]` are compatibility-only.

## Command routing tables (grouped by category)
EOF

    emit_routing_table_grouped "$src/commands" "$OPENCODE_PLATFORM" ".opencode/commands"
    emit_trigger_reference     "$src/commands" "$OPENCODE_PLATFORM"

    cat <<'EOF'

---

*Generated by adapters/opencode/adapter.sh - do not edit manually.*
EOF
  } > "$out"
}

_opencode_translate_commands() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  local f out
  for f in "$src"/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$OPENCODE_PLATFORM" || continue
    out="$dst/$(basename "$f")"
    cp "$f" "$out"
    rewrite_tool_neutral "$out"
    rewrite_platform_paths "$out" "$OPENCODE_DIR"
  done
}

_opencode_copy_references() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
  find "$dst" -type f -name '*.md' -print0 | while IFS= read -r -d '' f; do
    rewrite_platform_paths "$f" "$OPENCODE_DIR"
  done
}

_opencode_copy_scripts() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  mkdir -p "$dst"
  cp -R "$src/." "$dst/"
}

_opencode_emit_install_hint() {
  local dst="$1"
  cat > "$dst/INSTALL.md" <<'EOF'
# Install on OpenCode

```bash
# After running `bash scripts/build.sh --platform opencode`:
cp -R dist/opencode/. /path/to/your/vault/
```

Then in your vault:

- `AGENTS.md` is the operating manual OpenCode reads at session start.
- `.opencode/commands/*.md` are the command bodies the AI follows.
- `.opencode/scripts/` holds the Python helpers.

## Run on Hermes / open models

OpenCode is model-agnostic, so these commands run on any model you point it at,
including open models like Nous Research Hermes. No build changes needed - set
the model on OpenCode's side. Authenticate OpenRouter (`/connect`, or
`export OPENROUTER_API_KEY=...`), then in `opencode.json`:

```json
{
  "$schema": "https://opencode.ai/config.json",
  "model": "openrouter/nousresearch/hermes-4-70b",
  "provider": { "openrouter": { "models": { "nousresearch/hermes-4-70b": {} } } }
}
```

Use `nousresearch/hermes-4-405b` for the synthesis-heavy commands, or
`nousresearch/hermes-3-llama-3.1-405b:free` for a zero-cost trial. For full
privacy, run a smaller Hermes locally via Ollama / LM Studio. Core commands
(save, daily, capture, find, task, free-mode research) hold up well on open
models; the deep-synthesis commands prefer a stronger instruction-follower.
EOF
}
